import { defineConfig, devices } from '@playwright/test';
import { getBaseUrl } from './src/support/env';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  retries: 0,
  reporter: [['list'], ['html', { open: 'never' }]],
  use: {
    baseURL: getBaseUrl(),
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'setup',
      testMatch: /auth\.setup\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'auth',
      testDir: './tests/auth',
      testIgnore: /auth\.logout\.spec\.ts/,
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'catalog',
      testDir: './tests/catalog',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'search-filtering',
      testDir: './tests/search-filtering',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'product-details',
      testDir: './tests/product-details',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'product-management',
      testDir: './tests/product-management',
      dependencies: ['catalog', 'search-filtering', 'product-details'],
      workers: 1,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'basket',
      testDir: './tests/basket',
      testIgnore: /basket\.session\.spec\.ts/,
      dependencies: ['product-management'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'basket-session',
      testDir: './tests/basket',
      testMatch: /basket\.session\.spec\.ts/,
      dependencies: ['auth', 'basket'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'checkout',
      testDir: './tests/checkout',
      dependencies: ['basket', 'basket-session'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'orders',
      testDir: './tests/orders',
      dependencies: ['checkout'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'order-lifecycle',
      testDir: './tests/order-lifecycle',
      dependencies: ['orders'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'journeys',
      testDir: './tests/journeys',
      dependencies: ['order-lifecycle'],
      workers: 1,
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'auth-session',
      testDir: './tests/auth',
      testMatch: /auth\.logout\.spec\.ts/,
      dependencies: [
        'auth',
        'catalog',
        'search-filtering',
        'product-details',
        'product-management',
        'basket',
        'basket-session',
        'checkout',
        'orders',
        'order-lifecycle',
        'journeys',
      ],
      fullyParallel: false,
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
